### PR TITLE
Add Docker as a further installation option

### PR DESCRIPTION
**Pull request by tommy-muehle**
Hi @povils,
I "dockerized" your tool and want to share this also with you and the community.
Best,
Tommy

### CODE REVIEW

**Comment by exussum12** [comment]
Hi @tommy-muehle 

This is already dockerized through https://hub.docker.com/r/jakzal/phpqa/

The readme should probably be updated to reflect that ? (unless the project you made is different ?)

**Comment by tommy-muehle** [comment]
@exussum12 
I'm personally not a fan of phpqa because thats a very heavy all-in-one-image (645MB/uncompressed) without any specification/runtime environment for the individual tool. In comparison to mine 48 MB (also uncompressed) image which contains only related PHP extensions and settings. And phpqa misses also the possibility to have different Docker tags per version. See for example the [PHPStan image](https://github.com/phpstan/docker-image) which I also maintain.

But this is very subjective. So feel free to decide.

**Comment by exussum12** [comment]
Could you commit the docker file here ?

**Comment by tommy-muehle** [comment]
Is there anything I can do here?

**Comment by povils** [comment]
Hey @tommy-muehle , thanks for your input! Everything would be perfect except I dont like that on image build time composer is installing master version, which is not stable. I would prefer it would point to latest release :)

**Pull request closed without merging**
