### PR TITLE
Add function typehints and clean up composer json file

### PR DESCRIPTION
**Pull request by richardhughes**
Since version 2 bumps the PHP version up to 7.1 we can start using newer features like type hints and we can get rid of some of the dependencies in the composer json file.

All the tests pass with the changes 

```
PHPUnit 7.3.5 by Sebastian Bergmann and contributors.

.........................                                         25 / 25 (100%)

Time: 1.66 seconds, Memory: 20.00MB

OK (25 tests, 36 assertions)

```

### CODE REVIEW

**Comment by povils** [comment]
Hey, thanks for pull request! Could you also then remove PHPDocs there it is redundant?

**Comment by richardhughes** [comment]
Yeah no worries! I'll update it later tonight :)

**Comment by richardhughes** [comment]
Hey @povils, Removed the docblocks from the functions but AppVeyor seems to fail and I cant figure out why - Would you mind taking a look and letting me know? I'll update this PR with the fix :) Cheers!

**Comment by povils** [comment]
@raphaelstolt I will take a look. But it seems it has to do with Appveyor itself than your PR :)

**Pull request merged**
