### PR TITLE
Fix for missing tput binary

### PR DESCRIPTION
**Pull request by exussum12**
Fixes #159

### CODE REVIEW

**Comment by sidz** [comment]
what about to get rid of tputs and change a bit output format? see https://github.com/povils/phpmnd/pull/161

**Comment by exussum12** [comment]
Output format changes is harder, happy for a new output, but tools can depend on the output of this

**Comment by povils** [comment]
Yeah i would go with this approach first :)

**Review by povils — APPROVED** [review]

**Comment by sidz** [comment]
Thanks @exussum12

**Pull request merged**
