### PR TITLE
Support php-timer 4 and 5

### PR DESCRIPTION
**Pull request by twinh**
fix #109

### CODE REVIEW

**Review by exussum12 — APPROVED** [review]

**Comment by szepeviktor** [comment]
@povils Could you merge this one?
We cannot use phpmnd with modern Laravel.

**Comment by marc-jangvs** [comment]
Would be great if it could be merged.

**Comment by mhauri** [comment]
What's the status here @povils ?

**Review by maks-rafalko — APPROVED** [review]

**Comment by maks-rafalko** [comment]
So, I temporarily forked this repo and merged this PR.

I was able to use the fork like this in `composer.json`:

```diff
- "povils/phpmnd": "^2.3",
+ "povils/phpmnd": "dev-php-timer",

+ "repositories": [	
+     {	
+         "type": "vcs",	
+         "url": "https://github.com/maks-rafalko/phpmnd"	
+     }	
+ ]
```

If you want - you can use my fork while waiting to this PR is merged.
If you don't want - you can create your own fork and do exactly the same changes as above, but with the URL to your fork.

@povils hope you are doing ok, man. This repo needs some work from your side.

If you don't have time - consider adding more collaborators who can merge and release new versions. Otherwise community will have to fork this repo completely, which I would like to avoid.

**Comment by povils** [comment]
Hey! sorry for the delayed response:) LGTM

**Comment by szepeviktor** [comment]
Thank you.

**Comment by maks-rafalko** [comment]
@povils could you please release the new version?

**Pull request merged**
