### PR TITLE
Update the composer version to PHP7.2

### PR DESCRIPTION
**Pull request by richardhughes**
This change will update the composer version to php7.2 and update phpunit to v8

Support for 7.1 has ended so we should upgrade to 7.2 - Security support for 7.2 will end in Nov 2020

### CODE REVIEW

**Comment by richardhughes** [comment]
`PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

............................                                      28 / 28 (100%)

Time: 116 ms, Memory: 20.00 MB

OK (28 tests, 42 assertions)
`

**Comment by exussum12** [comment]
Bumping versions isn't a a BC break. https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

**Comment by kubawerlos** [comment]
It is for PHPUnit.

Anyways, these changes have no reason to drop support of PHP 7.1. If you introduce a feature not supported in PHP 7.1 then fine, but not with these changes.

**Comment by exussum12** [comment]
It's what the sat solver is for. This really isn't a BC break.

**Comment by aaajeetee** [comment]
I think this PR is now duplicate because #105 is merged. Correct me if I'm wrong.

**Pull request closed without merging**
