### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by exussum12**
Bump version to 3.5.0 ready for release

### CODE REVIEW

**Comment by sidz** [comment]
It would be nice to merge https://github.com/povils/phpmnd/pull/176 to avoid setting version manually. WDYT?

**Comment by exussum12** [comment]
Approved, merge that and then tag?

**Comment by sidz** [comment]
Yeah. I'll rebase it against latest master later today in order fix conflicts.

**Comment by exussum12** [comment]
Rebased and fixed merge conflicts now should be ready to go. Thanks for the work on it :)

**Pull request merged**
