### PR TITLE
Update release number

### PR DESCRIPTION
**Pull request by exussum12**
New release will be 3.0.1

### CODE REVIEW

**Review by kubawerlos — CHANGES_REQUESTED** [review]
@exussum12 can you fix the checks?

**Comment by sidz** [comment]
need to merge https://github.com/povils/phpmnd/pull/160 first

**Review by kubawerlos — APPROVED** [review]

**Comment by exussum12** [comment]
Approved, can likely release both

**Comment by sidz** [comment]
160 has been merged. So please rebase your branch against master.

IMO it would be nice to merge https://github.com/povils/phpmnd/pull/161 in case you would like to release 3.0.1.

**Review by sidz — APPROVED** [review]

**Pull request merged**
