### PR TITLE
Add PHP-Parser 5 support

### PR DESCRIPTION
**Pull request by sidz**
This PR adds PHP-Parser 5 support

### CODE REVIEW

**Comment by exussum12** [comment]
Should it be current version rather than newest version ?

**Comment by sidz** [comment]
Hey @exussum12.

`createForNewestSupportedVersion` is an equivalent to previous behavior `$factory->create(ParserFactory::PREFER_PHP7)`  see Upgrade guide: https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-5.0.md

**Comment by exussum12** [comment]
createForHostVersion() was what I was thinking but happy either way

**Review by exussum12 — DISMISSED** [review]

**Comment by sidz** [comment]
Yeah, you are right. Replaced to `createForHostVersion`

**Review by exussum12 — APPROVED** [review]

**Pull request merged**
