### PR TITLE
Ignore negative values when the scalar has no value attribute

### PR DESCRIPTION
**Pull request by devinpearson**
fix for #92

### CODE REVIEW

**Comment by exussum12** [comment]
were you using dev-master to come across this ?

**Comment by exussum12** [comment]
Just checked, yeah its dev-master. I have made a slightly different check, which doesnt return (there could be a magic number still hidden with the return). Mine checks that it is a number to get in to this section

**Comment by exussum12** [comment]
Fix included https://github.com/povils/phpmnd/pull/86

**Comment by devinpearson** [comment]
no problem I didnt dig much deeper than fixing it for my scenario.

**Comment by povils** [comment]
Thanks for PR!!

**Pull request merged**
